---
- name: Install Zabbix repository package
  ansible.builtin.apt:
    deb: "{{ zabbix_repo_deb_url }}"
    state: present

- name: Update apt cache after adding repo
  ansible.builtin.apt:
    update_cache: yes
  changed_when: false

- name: Install Zabbix Agent
  ansible.builtin.apt:
    name: zabbix-agent
    state: present
